# Generated by Django 3.0.5 on 2020-05-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('manpower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Projects'),
        ),
    ]
