# Generated by Django 3.0.5 on 2020-05-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0002_labour_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='labourDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50,
                                                 null=True, verbose_name='Labour Designation')),
            ],
        ),
        migrations.CreateModel(
            name='labourSkillType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=50,
                                                null=True, verbose_name='Labour Skill Type')),
                ('skill_type_amount', models.CharField(
                    max_length=50, null=True, verbose_name='Skill Type Amount')),
            ],
        ),
        migrations.AlterField(
            model_name='labour',
            name='aadhar_photo',
            field=models.FileField(
                blank=True, upload_to='', verbose_name='Aadhar Card Photo'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='image',
            field=models.FileField(
                upload_to='', verbose_name='Labour Profile Picture'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='tech_certi',
            field=models.FileField(
                blank=True, upload_to='', verbose_name='Technical Certificate Upload'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='ten_certi',
            field=models.FileField(
                upload_to='', verbose_name='10th Certificate Upload'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='twelve_certi',
            field=models.FileField(
                upload_to='', verbose_name='12th Certificate Upload'),
        ),
        migrations.AddField(
            model_name='labour',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL,
                                    to='manpower.labourDesignation', null=True, verbose_name='Labour Designation'),
        ),
        migrations.AddField(
            model_name='labour',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL,
                                    to='manpower.labourSkillType', null=True, verbose_name='Labour Skill Type'),
        ),
    ]
