# Generated by Django 3.0.5 on 2020-05-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0003_auto_20200510_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='manpower.labourDesignation', verbose_name='Labour Designation'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='skill_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='manpower.labourSkillType', verbose_name='Labour Skill Type'),
        ),
    ]
