# Generated by Django 3.0.5 on 2020-05-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0005_auto_20200510_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourdesignation',
            options={'verbose_name': 'Labour Designation', 'verbose_name_plural': 'Labour Designation'},
        ),
        migrations.AlterModelOptions(
            name='labourskilltype',
            options={'verbose_name': 'Labour Skill Type', 'verbose_name_plural': 'Labour Skill Type'},
        ),
        migrations.RemoveField(
            model_name='labour',
            name='email',
        ),
    ]
