# Generated by Django 3.0.5 on 2020-05-10 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projectrepeter_remarks'),
        ('manpower', '0006_auto_20200511_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='alter_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Number'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='highest_qual_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Proof of Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Labour Profile Picture'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='pan_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='PAN Card Photo'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='labour',
            name='tech_certificate_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Technical Certificate Name'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='ten_certi',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='10th Certificate Upload'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='twelve_certi',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='12th Certificate Upload'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('R', 'R')], default=None, max_length=10, verbose_name='Shift')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.labour')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects')),
            ],
            options={
                'verbose_name': 'Attandance',
                'verbose_name_plural': 'Attandance',
            },
        ),
    ]
