# Generated by Django 3.0.5 on 2020-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0007_auto_20200511_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(upload_to='', verbose_name='Company Profile Picture')),
            ],
        ),
    ]
