# Generated by Django 3.0.5 on 2020-05-12 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200512_1651'),
        ('manpower', '0009_auto_20200512_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=None, max_length=10, verbose_name='Overtime'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manpower.SuperVisors'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Attendance Date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Projects'),
        ),
    ]
