# Generated by Django 3.0.5 on 2020-05-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0010_auto_20200513_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overtime',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=None, max_length=12, verbose_name='Overtime'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('R', 'R')], default=None, max_length=12, verbose_name='Shift'),
        ),
    ]
