# Generated by Django 3.0.5 on 2020-05-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0011_auto_20200513_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='supervisor',
        ),
    ]
