# Generated by Django 3.0.5 on 2020-05-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0012_remove_attendance_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='labour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manpower.labour'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=None, max_length=12, null=True, verbose_name='Overtime'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('R', 'R')], default=None, max_length=12, null=True, verbose_name='Shift'),
        ),
    ]
