# Generated by Django 3.0.5 on 2020-05-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200509_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstart',
            name='security_deposit',
        ),
        migrations.AddField(
            model_name='security_deposit',
            name='project',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Projects'),
        ),
        migrations.AlterField(
            model_name='projectrepeter',
            name='from_date',
            field=models.DateField(default='2020-04-08',
                                   verbose_name='From Date'),
        ),
    ]
