# Generated by Django 3.0.5 on 2020-05-07 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200508_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectp2',
            name='doc_handover_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 42, 10, 341775, tzinfo=utc), verbose_name='All Document Handover Date'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_start_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 42, 10, 340777, tzinfo=utc), null=True, verbose_name='Project Start Date'),
        ),
    ]
