# Generated by Django 3.0.5 on 2020-05-07 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200508_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectp2',
            old_name='doc_handover_to',
            new_name='doc_handover_person',
        ),
        migrations.AddField(
            model_name='projectp2',
            name='doc_handover_option',
            field=models.CharField(choices=[('Assistant', 'Assistant'), ('Engineer', 'Engineer'), ('Division Office', 'Division Office'), ('Supervisor', 'Supervisor')], default=None, max_length=200, verbose_name='All Document Handover to (Options)'),
        ),
        migrations.AlterField(
            model_name='projectp2',
            name='doc_handover_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='All Document Handover Date'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Project Start Date'),
        ),
    ]
