# Generated by Django 3.0.5 on 2020-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200509_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrepeter',
            name='from_date',
            field=models.DateField(default='2020-04-08T19:43:45.148448+00:00', verbose_name='From Date'),
        ),
    ]
