# Generated by Django 3.0.5 on 2020-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200509_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrepeter',
            name='from_date',
            field=models.DateField(default='2020-04-09', verbose_name='From Date'),
        ),
    ]
