# Generated by Django 3.0.5 on 2020-05-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0001_initial'),
        ('project', '0004_auto_20200508_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='superviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manpower.SuperVisors'),
        ),
        migrations.CreateModel(
            name='superdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.SuperVisors')),
            ],
        ),
    ]
