# Generated by Django 3.0.5 on 2020-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200509_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstart',
            name='ai_upload',
            field=models.FileField(null=True, upload_to='', verbose_name='Agreement & Indemnity Bond Upload'),
        ),
    ]
