# Generated by Django 3.0.5 on 2020-05-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200509_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfollowup',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=100, verbose_name='Follow Up Status'),
        ),
        migrations.AlterField(
            model_name='projectrepeter',
            name='from_date',
            field=models.DateField(default='2020-04-10', verbose_name='From Date'),
        ),
    ]
