# Generated by Django 3.0.5 on 2020-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200510_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfollowup',
            name='followup_by',
        ),
        migrations.RemoveField(
            model_name='projectfollowup',
            name='followup_remarks',
        ),
        migrations.RemoveField(
            model_name='projectfollowup',
            name='followup_to',
        ),
        migrations.AddField(
            model_name='projectfollowup',
            name='bill_position',
            field=models.CharField(choices=[('Assistant Engineer', 'Assistant Engineer'), ('Executive Engineer - Division', 'Executive Engineer - Division'), ('Regional Account Office', 'Regional Account Office')], default='Regional Account Office', max_length=100, verbose_name='Bill Position'),
        ),
    ]
