# Generated by Django 3.0.5 on 2020-05-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200510_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrepeter',
            name='from_date',
            field=models.DateField(default='2020-04-11', verbose_name='From Date'),
        ),
    ]
