# Generated by Django 3.0.5 on 2020-05-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200511_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepeter',
            name='Remarks',
            field=models.CharField(max_length=50, null=True, verbose_name='Project Repeter Remarks'),
        ),
    ]
